service: team-1-final-project
plugins:
  - serverless-python-requirements

provider:
  name: aws
  stage: dev
  region: eu-west-1
  role: arn:aws:iam::670948818876:role/ServerlessResourcesRole

package:
  individually: true

functions:
  redshift-lambda:
    runtime: python3.8
    handler: handler_etl.start
    module: redshift_lambda
    vpc:
      securityGroupIds:
        - !ImportValue RedshiftAndVPC-VPCSecurtiyGroup
      subnetIds:
        - !ImportValue RedshiftAndVPC-VPCPrivateSubnet
    environment:
      DB_HOST: !ImportValue RedshiftAndVPC-ClusterAddress
      DB_USER: team1
      DB_PORT: !ImportValue RedshiftAndVPC-ClusterPort
      DB_NAME: team1db
      DB_CLUSTER: !ImportValue RedshiftAndVPC-ClusterID
  users:
    handler: handler_etl.start
    events:
      - s3:
        bucket: cafe-data-data-pump-dev-team-1
        event: s3:ObjectCreated:*
        rules:
          - suffix: .csv
        existing: true
      